### ISSUE TITLE
Errors while running autogen.sh

### ISSUE THREAD

**Issue by rahul-desai3** [kazuki/opus.js-sample#2]
I am using Cygwin with Git installed in it to setup this project on my machine loacally. 

While following the steps mentioned in the readme, I encountered errors while doing ./autogen.sh
Cygwin wasnt able to recognize the autoreconf command in the shell script so I replaced it with autoconf after installing autoconf module for Cygwin.

After doing that, I am now getting following error:
autoconf-2.69: error: invalid option `-isf'

**Comment by kazuki** [comment]
Please use Linux environment. (VirtualBox, VMware, Hyper-V, ...)
