### ISSUE TITLE
Autogen not found?

### ISSUE THREAD

**Issue by izy521** [kazuki/opus.js-sample#5]
``` bash
cd ./native/opus; ./autogen.sh
/bin/sh: 1: ./autogen.sh: not found
make: *** [native/opus/configure] Error 127
```

This is the error I get when trying to `make`. Anything I'm doing wrong?

**Comment by Rillke** [comment]
- Did you init/ clone all submodules?
- Is there a file named `./native/opus/autogen.sh`?
- Is the file named `./native/opus/autogen.sh` executable for the user you are attempting to execute it under?

**Comment by Rillke** [comment]
There is an executable [autogen.sh](http://git.xiph.org/?p=opus.git;a=blob;f=autogen.sh;h=942ba098a210666280e924f86f70383aacaddb52;hb=HEAD) in [`3a1dc9d`](http://git.xiph.org/?p=opus.git;a=tree;h=3a1dc9d). Which revision of opus have you checked out?

**Comment by izy521** [comment]
Ah forgive me, I'm still pretty new to Git altogether. I just followed the instructions on the main page and used `git clone https://github.com/kazuki/opus.js-sample.git`. There is nothing in the `./native/opus` folder.
![opus_031](https://cloud.githubusercontent.com/assets/8113211/11021179/64f97330-864a-11e5-815f-c95f5a888c4b.png)

Maybe I missed cloning the submodules? How would I go about doing that?

**Comment by izy521** [comment]
I seem to have got it now, I had to add the `--recursive` flag. Thanks for your help!

**Comment by Rillke** [comment]
You're welcome! I think the [instructions](https://github.com/kazuki/opus.js-sample/pull/6/files) need to be updated in this regard or the make file must ensure the submodules are present. Not your fault, thanks for asking and welcome to Git. Once you know it (plan 2 years at least), you'll love it.
