### ISSUE TITLE
emconfigure: command not found

### ISSUE THREAD

**Issue by seant-ca** [kazuki/opus.js-sample#8]
Hi there, when I try to run "make", I get this error:
`
cd ./native/opus; emconfigure ./configure --disable-extra-programs --disable-doc
/bin/sh: emconfigure: command not found
`

Here is other output:

`
cd ./native/opus; ./autogen.sh
Updating build configuration files, please wait....
glibtoolize: putting auxiliary files in '.'.
glibtoolize: linking file './ltmain.sh'
glibtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
glibtoolize: linking file 'm4/libtool.m4'
glibtoolize: linking file 'm4/ltoptions.m4'
glibtoolize: linking file 'm4/ltsugar.m4'
glibtoolize: linking file 'm4/ltversion.m4'
glibtoolize: linking file 'm4/lt~obsolete.m4'
configure.ac:38: installing './compile'
configure.ac:36: installing './config.guess'
configure.ac:36: installing './config.sub'
configure.ac:33: installing './install-sh'
configure.ac:33: installing './missing'
Makefile.am:259: warning: '%'-style pattern rules are a GNU make extension
Makefile.am:262: warning: '%'-style pattern rules are a GNU make extension
Makefile.am: installing './INSTALL'
Makefile.am: installing './depcomp'
parallel-tests: installing './test-driver'
cd ./native/opus; emconfigure ./configure --disable-extra-programs --disable-doc
/bin/sh: emconfigure: command not found
make: *** [native/opus/Makefile] Error 127

`

I installed emscripten SDK where can I find the "emconfigure" command?

**Comment by chris-rudmin** [comment]
emconfigure needs to be added to your PATH. On mac/linux it would be this command `source ./emsdk_env.sh`

**Comment by seant-ca** [comment]
Thanks @chris-rudmin
